{
 "title": "ML API Dashboard",
 "description": "Machine learning-specific metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Model Versions",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(live_model, live_version, shadow_model, shadow_version, version)(model_version_details_info\n* on (instance, job) group_left(version)\npython_info)",
     "legendFormat": "{{model_version}}"
    }
   ]
  },
  {
   "title": "Average Predicted Cardio Disease Probablity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardio_vascular_disease_probablities_sum[5m])/rate(cardio_vascular_disease_probablities_count[5m])",
     "legendFormat": "Average Prediction Amount ($)"
    }
   ]
  },
  {
   "title": "Average Predicted Cardio Disease Probablity\n Rate (/second)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardio_vascular_disease_probablities_count[10m])",
     "legendFormat": "Average Prediction Rate"
    }
   ]
  },
  {
   "title": "Percentage of Negative Predicted People",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    {
     "expr": "rate(cardio_vascular_disease_negative[10m])/rate(no_of_patients_total[10m])*100",
     "legendFormat": "Cardio Disease Prediction Probablity"
    }
   ]
  },
  {
   "title": "Percentage of Positive Predicted People",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "rate(cardio_vascular_disease_positive[10m])/rate(no_of_patients_total[10m])*100",
     "legendFormat": "Cardio Disease Prediction Probablity"
    }
   ]
  }
 ]
}